[CLOUDTRUST-3208] Support of multiple issuers for OIDC token provider
cloudtrust/keycloak-client pull request #86
Opened 2021-05-20 08:05 UTC by fperot74

Changes are supposed to be backward compatible

2021-05-27 09:35 UTC, harture requested changes

2021-05-27 09:35 UTC, harture commented on toolbox/oidc_connect.go
> +	var targets = map[string]string{key: config.AddrTokenProvider[0]}
Why wew do not use the map with the default key instead of this convention of using the first ?

2021-05-28 08:27 UTC, fperot74 commented on toolbox/oidc_connect.go
> +	var targets = map[string]string{key: config.AddrTokenProvider[0]}
Disappeared with new version

2021-05-28 15:28 UTC, harture approved these changes

2021-05-28 15:50 UTC, merged